### ISSUE TITLE
DMI block 1 not found in file "I370MS.BIN".

### ISSUE THREAD

**Issue by lansend** [Shmurkio/LenovoDMIDecryptor#2]
I've tried different files, including those exported using Intel FTPW and the official BIOS files, but none have worked. The message "DMI block 1 not found in file" is displayed.

**Comment by lansend** [comment]
[Uploading I370MS.zip…]()

**Comment by Shmurkio** [comment]
The error indicates that it couldn't find the "LENV" signature that initializes the DMI in your BIOS dump. You didn't upload a BIOS dump (the link redirects to this repo), but I looked at an update for your motherboard (I370MS), it seems to be AMI and only InsydeH2O BIOSes have the "LENV" signature. Did you try searching for the DMI in UEFITool? It might not be encrypted at all.

**Comment by lansend** [comment]
Sorry, I uploaded the file again, and the BIOS is an AMI BIOS.
[I370MS.zip](https://github.com/Shmurkio/LenovoDMIDecryptor/files/15418252/I370MS.zip)

**Comment by Shmurkio** [comment]
Your DMI can be found in the Freeform "SMBiosStaticData", search for the GUID "DAF4BF89CE714917B522C89D32FBC59F" (Header only) with UEFITool:
![image](https://github.com/Shmurkio/LenovoDMIDecryptor/assets/112756303/b5b4574f-bf28-4433-a381-afd2eb071a8f)
Your data can be found in the order of the standard SMBIOS structure:
Table 0 (BIOS):
Vendor: LENOVO
Version: 5.13
Release date: 10/24/2018
Table 1 (System):
Manufacturer: LENOVO
Product Name: INVALID
Version: Lenovo Product
Serial Number: INVALID
SKU Number: Default string
Family: Lenovo Product
etc...

Nothing is encrypted here, you can simply use a HEX editor. I don't know if there's a checksum though.

**Comment by Shmurkio** [comment]
I'm closing this issue because it is not related to the program.
